// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'body': string;
  'container': string;
  'content': string;
  'detected': string;
  'done': string;
  'image': string;
  'installButton': string;
  'lead': string;
  'note': string;
  'number': string;
  'quick': string;
  'step': string;
  'steps': string;
  'tab': string;
  'tabs': string;
  'textStep': string;
}
export const cssExports: CssExports;
export default cssExports;
