version: 2
jobs:
  build:
    docker:
      - image: node:6
    steps:
      - checkout
      - run: sh build.sh
      - persist_to_workspace:
          root: aws/lambda/forecast/.build
          paths:
            - forecast.zip
  deploy:
    docker:
      - image: cnadiminti/aws-sam-local
    steps:
      - checkout
      - run: sh deploy.sh
    #  - run: aws cloudformation deploy --stack-name rainclock --template-file aws/cf/templates/rainclock.yaml --capabilities CAPABILITY_IAM
    #  - run: aws s3 sync public s3://rainclock-rainclockpublicbucket-16zshove7uwcq/ --delete
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
