version: 2
jobs:
  build:
    docker:
      - image: node:6
    steps:
      - run: apt-get update
      - run: apt-get install zip -qy
      - checkout
      - run: sh build.sh
      - persist_to_workspace:
          root: .
          paths:
            - aws/lambda/forecast/.build/forecast.zip
  deploy:
    docker:
      - image: cnadiminti/aws-sam-local
    steps:
      - run: apk --update add ca-certificates
      - checkout
      - attach_workspace:
          at: .
      - run: sh deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
