// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'location': string;
  'reset': string;
}
export const cssExports: CssExports;
export default cssExports;
