// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorRow': string;
  'container': string;
  'legend': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
