// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'coffee': string;
  'container': string;
  'content': string;
  'credits': string;
}
export const cssExports: CssExports;
export default cssExports;
